# Generated by Django 5.0.6 on 2025-08-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('habitaciones', models.PositiveIntegerField(default=1)),
                ('banos', models.PositiveIntegerField(default=1)),
                ('metros_cuadrados', models.PositiveIntegerField(default=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='casas/')),
                ('publicado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
